margelo/react-native-quick-crypto

package.json

Was experiencing multiple errors like this while trying to webpack code for react-native:
The `react-native` field in package.json needs to point to the lib folder instead of src folder. Like [react-native-mmkv](https://github.com/mrousavy/react-native-mmkv/blob/master/package.json) for example

fix: package.json react-native source path

---

src/Utils.ts

It seems like this should just be inverted, unless I'm missing something? I'm unable to pass any valid values to options.hash  or options.hashAlgorithm for generateSigningKeyPair, etc.

Fix incorrect validateString check.

---

package.json
src/Cipher.ts
src/Utils.ts
yarn.lock

@mrousavy asked me to fix the types for cipher in #245 so I took a crack at it
Node uses a type called CipherKey which is a combination of BinaryLike and a new class called KeyObject. I am not sure if we support KeyObject but we're forced to declare support for it if we want to follow Node's type definitions for crypto. 
I added a TODO in case it should be supported in the conversion util

types: improve cipher types

---

cpp/Cipher/MGLCipherHostObject.cpp

- Replaced missing var with currently used validation.
Original code from node/crypto:
https://github.com/nodejs/node/blob/9ef03f1c237f509cb965d90c5cb301e99be80208/src/crypto/crypto_cipher.cc#L597
Var used by react-native-quick-crypto:
https://github.com/margelo/react-native-quick-crypto/blob/96df943a89ddbd92c3067edd725fc57aa4633e07/cpp/Cipher/MGLCipherHostObject.cpp#L609

Fixed missing var for OpenSSL 3.+

---

example/src/testing/Tests/CipherTests/CipherTestSecond.ts
src/Cipher.ts

authTagLength was set equal to -1, which would result in an auth tag length of 4294967295, way above the Hermes limit of 256 MB

fix: getAuthTag returning a value of -1 bytes

---

src/index.ts

bug in rc1 where cjs export is broken when global namespace is used

fix: broken cjs export

---

example/ios/Podfile.lock
example/src/testing/Tests/webcryptoTests/import_export.ts
src/Utils.ts
src/subtle.ts

`subtle.importKey` was not supporting `AlgorithmIdentifier` type of `SubtleAlgorithm | AnyAlgorithm`, just `SubtleAlgorithm`.  So you would get an error when you try something like this:
```ts
const key = await subtle.importKey(
'raw',
keyData,
'AES-GCM',   // <- string, not object
false,
['encrypt', 'decrypt'],
);
```
Strings (of supported algorithms, i.e. `AnyAlgorithm`) should be valid for the `algorithm` argument.  This PR fixes the bug.

fix: subtle importKey algorithm as string

---

package.json
src/keys.ts

`package.json` had the `react-native` directive pointing to lib, not src.
While testing in RN app, a less-than-desscriptive message ate some time for `key` argument type.  Added a bit more detail as well as typescript annotations.

fix: rn source import corrected, key argument type error

---

package.json
tsconfig.json

for consideration as an alternative to #294 
rather than requiring downstream projects to use typescript and transpile typescript using their own project's settings, we should transpile the typescript in this project and ship ESM with declarations, sourceMaps, and declarationMaps

use transpiled esm for app bundles

---

android/CMakeLists.txt
android/build.gradle
example/ios/Podfile.lock
example/src/testing/Tests/webcryptoTests/import_export.ts

I commented out gradle's handling of the `NODE_MODULES_DIR` environment variable in #233 for some unknown reason 🤡 .
This PR puts that mechanism back, and hopefully handles the following:
fixes #291 
closes #297
Also, this fixes a regression in a `subtle.importKey` test, introduced in #294

fix: android node_modules

---

example/android/build.gradle

fix: minSdkVersion being below that of the latest react native release

---

example/src/testing/Tests/webcryptoTests/import_export.ts
src/Utils.ts
src/keys.ts
src/random.ts

This PR adds support for keys such as uint8array for the `prepareSecretKey` method, I noticed while trying to generate a mnemonic with the following code:
```ts
import { generateMnemonic as generateBIP39Mnemonic } from '@scure/bip39';
import { wordlist } from '@scure/bip39/wordlists/english';
```
That due to the checks within `prepareSecretKey`, keys in the format of Uint8Array were not supported and this generated the following exception:
```
Invalid argument type for "key". Need ArrayBuffer, KeyObject, CryptoKey, string
```

feat: add support for Uint8Array

---

cpp/Cipher/MGLGenerateKeyPairInstaller.cpp
cpp/Cipher/MGLGenerateKeyPairSyncInstaller.cpp
cpp/Cipher/MGLRsa.cpp
cpp/Cipher/MGLRsa.h
cpp/JSIUtils/MGLJSIUtils.h
cpp/MGLKeys.cpp
cpp/MGLKeys.h
cpp/Utils/MGLUtils.cpp
cpp/Utils/MGLUtils.h
cpp/webcrypto/MGLWebCrypto.cpp
cpp/webcrypto/crypto_ec.cpp
cpp/webcrypto/crypto_ec.h
example/ios/Podfile.lock
example/package.json
example/src/hooks/useTestList.ts
example/src/testing/Tests/webcryptoTests/generateKey.ts
example/src/testing/Tests/webcryptoTests/import_export.ts
example/yarn.lock
implementation-coverage.md
package.json
src/Cipher.ts
src/NativeQuickCrypto/Cipher.ts
src/NativeQuickCrypto/NativeQuickCrypto.ts
src/Utils.ts
src/ec.ts
src/keys.ts
src/subtle.ts

Add support for `subtle.generateKey()` for `EC` formats (ECDSA, ECDH)
closes #59 
closes #80 
closes #288

feat: `subtle.generateKey` support for `ecdsa`, `ecdh`

---

cpp/Cipher/MGLRsa.cpp
cpp/Cipher/MGLRsa.h
cpp/MGLKeys.cpp
cpp/MGLKeys.h
cpp/Utils/MGLUtils.cpp
cpp/Utils/MGLUtils.h
cpp/webcrypto/MGLWebCrypto.cpp
cpp/webcrypto/MGLWebCrypto.h
cpp/webcrypto/crypto_ec.cpp
cpp/webcrypto/crypto_ec.h
example/src/testing/Tests/webcryptoTests/generateKey.ts
example/src/testing/Tests/webcryptoTests/import_export.ts
example/src/testing/fixtures/keys/ec_p256_private.ts
example/src/testing/fixtures/keys/ec_p256_public.ts
implementation-coverage.md
src/Cipher.ts
src/Hashnames.ts
src/NativeQuickCrypto/Cipher.ts
src/NativeQuickCrypto/NativeQuickCrypto.ts
src/NativeQuickCrypto/webcrypto.ts
src/Utils.ts
src/index.ts
src/keys.ts
src/rsa.ts
src/sig.ts
src/subtle.ts
src/webcrypto.ts
test/hashnames.test.ts

Adds the following functionality:
* `subtle.exportKey()` `pkcs8` `ec`
* `subtle.exportKey()` `pkcs8` `rsa`
* `subtle.exportKey()` `spki` `rsa`
* `subtle.generateKey()` `rsa`
* `subtle.importKey()` `spki` `rsa`
Exposes the following in the public API:
* `crypto.createPrivateKey()`
* `crypto.createPublicKey()`
* `crypto.createSecretKey()`
* `webcrypto.CryptoKey` class
fixes #287 
fixes #356

feat: `subtle` `rsa` `spki` work

---

.github/workflows/build-android.yml
.github/workflows/build-ios.yml
.github/workflows/validate-android.yml
.github/workflows/validate-cpp.yml
.github/workflows/validate-js.yml
src/Utils.ts

Separating the `0.x` and `main` branches for Nitro Modules / new architecture means that we need to run GHA on both of them going forward.  The workflows were configured to only run on `main`.

chore: run GHA on `0.x` branch too

---

example/src/testing/tests/CipherTests/CipherivDecipheriv.ts
src/Cipher.ts

This fixes `getAuthTag` returning an `ArrayBuffer` (unexpected) instead of a `Buffer` (expected).
Node `crypto` has been returning `Buffer` since at least Node 16:
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v16/crypto.d.ts#L927
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v18/crypto.d.ts#L956
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v20/crypto.d.ts#L960
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/crypto.d.ts#L918
Note: I wasn't sure whether to do this on the 0.x branch or main. Let me know if you want me to update the target branch.

fix: return `Buffer` from `getAuthTag`

---

src/Hashnames.ts
test/hashnames.test.ts

When we call Crypto.subtle.verify, we need to pass verifyAlgorithm like this:
```javascript
const verifyAlgorithm = {
name: 'ECDSA',
hash: { name: 'SHA-256' },
};
return crypto.subtle.verify(verifyAlgorithm, key, signature, data);
```
In this case, `algo.toString().toLowercase()` will not work.
This PR resolves the problem.

fix: when algo is an object of SubtleAlgorithm

---

ios/QuickCryptoModule.mm

Fixes https://github.com/margelo/react-native-quick-crypto/issues/462 by applying https://github.com/mrousavy/react-native-mmkv/pull/602
I am on RN 0.74 with Expo SDK 51, and on iOS as soon as I reload the iOS app (e.g. pressing `r` on the device or Expo CLI) the app throws the error
> Failed to install react-native-quick-crypto, the native initializer function does not exist. Are you trying to use QuickCrypto from different JS Runtimes?

fix: Retrieval of bridge on iOS when reloading the app

---

android/build.gradle

Had this issue while using this package in a project created with react-native 0.76.
I've tested this fix myself and everything is working fine in my project.

fix: excluded libreactnative.so (#506)

---

cpp/JSIUtils/MGLTypedArray.cpp
example/ios/Podfile.lock

This is "fine" for now, will be fixed properly by using Nitro in `1.x` and higher.

fix: stop a crash in HostObject dtor

---

android/build.gradle

fix: bump OpenSSL dependency for Android

---

packages/react-native-quick-crypto/android/build.gradle

When trying to implement UI tests for Android I got the following error:
```
Execution failed for task ':react-native-quick-crypto:mergeDebugAndroidTestJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
> 2 files found with path 'META-INF/com.android.tools/proguard/coroutines.pro' from inputs:
- ~/.gradle/caches/8.8/transforms/63fe3045b8abd462b74b6e64f9d86a35/transformed/jetified-kotlinx-coroutines-core-jvm-1.6.1.jar
- ~/.gradle/caches/8.8/transforms/dc8560c5b960aeb173e49bf1b90f8764/transformed/jetified-kotlinx-coroutines-android-1.6.1.jar
```
The new unreleased version 1.0.0 [already contains this fix](https://github.com/margelo/react-native-quick-crypto/blob/main/packages/react-native-quick-crypto/android/build.gradle#L81-L8 …

fix: assembleAndroidTest building

---

.clang-format
.github/workflows/validate-cpp.yml
package.json
packages/react-native-quick-crypto/cpp/ed25519/HybridEdKeyPair.cpp
packages/react-native-quick-crypto/cpp/ed25519/HybridEdKeyPair.hpp
packages/react-native-quick-crypto/cpp/hash/HybridHash.cpp
packages/react-native-quick-crypto/cpp/hash/HybridHash.hpp
packages/react-native-quick-crypto/cpp/pbkdf2/HybridPbkdf2.cpp
packages/react-native-quick-crypto/cpp/pbkdf2/HybridPbkdf2.hpp
packages/react-native-quick-crypto/cpp/random/HybridRandom.cpp
packages/react-native-quick-crypto/cpp/random/HybridRandom.hpp
packages/react-native-quick-crypto/cpp/utils/Utils.hpp
scripts/clang-format.sh

`bun clang-format` and lint C++ files on CI should expect/produce the same output.

fix: clang format ci

---

example/ios/Podfile.lock
example/src/tests/hash/hash_tests.ts
packages/react-native-quick-crypto/src/hash.ts

pulled out from #607 
| iOS | Android |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/cba351ea-5c86-4786-9c60-7bcb1755414c" height="600px" /> | <img src="https://github.com/user-attachments/assets/1121888a-3f45-424b-8873-f4b7ad34f65d" height="600px" /> |

refactor: validate hash args

---

packages/react-native-quick-crypto/src/pbkdf2.ts

Hi,
I found a regression in 0.x.
`pbkdf2Sync` has been returning `Buffer`, but v0.7.13 returns `Uint8Array`.
`pbkdf2` still returns `Buffer`.
This commit broke the behavior: https://github.com/margelo/react-native-quick-crypto/commit/889498318ac96ee1f243b2be39e33f4be92cf32c
But I couldn't find any reason for this change.
On the main branch, the return type of `pbkdf2Sync` is `Buffer`, so I think this is a mistake.
https://github.com/margelo/react-native-quick-crypto/blob/83d2aed323b2182c10c5943d29fb84e9a0b5405b/packages/react-native-quick-crypto/src/pbkdf2.ts#L77
@boorad Can you check it?

Fix inconsistent return type of pbkdf2

---

packages/react-native-quick-crypto/deps/fastpbkdf2/fastpbkdf2.c

This change updates the platform check to correctly include <machine/endian.h> when building for Mac Catalyst.

fix: include correct endian header for Mac Catalyst builds

---

packages/react-native-quick-crypto/android/build.gradle

I've rebuilt the maven libs for both sodium and openssl with 16 KB page size enabled.
closes #759

feat: updates sodium and openssl version for 16 KB page size support

---

bun.lock
example/ios/Podfile.lock
example/src/tests/hash/hash_tests.ts
packages/react-native-quick-crypto/QuickCrypto.podspec
packages/react-native-quick-crypto/cpp/hash/HybridHash.cpp
packages/react-native-quick-crypto/cpp/hash/HybridHash.hpp
packages/react-native-quick-crypto/nitrogen/generated/shared/c++/HybridHashSpec.cpp
packages/react-native-quick-crypto/nitrogen/generated/shared/c++/HybridHashSpec.hpp
packages/react-native-quick-crypto/src/hash.ts
packages/react-native-quick-crypto/src/specs/hash.nitro.ts

The createHash('KECCAK-256') function was failing with "Unknown hash algorithm" error on iOS, even though getHashes() listed KECCAK-256 as available. This was caused by a mismatch between the legacy OpenSSL API (EVP_get_digestbyname) used in createHash() and the provider-based API that enumerates available algorithms.
Added a dedicated keccak256() function that uses OpenSSL's modern provider-aware API (EVP_MD_fetch) to properly access KECCAK-256 digests. Also added unit test.
This could be extended to support all hash functions using the new OpenSSL API, but this satisfied my needs for my project. I might also add a PR to extend keccak256 support to the legacy 0.7.15 package because that is what everyone is using on npm (however as I understand it this would require upgrading the OpenSSL …

feat: Add native keccak256 hash function from OpenSSL 3.x

---

.rules
bun.lock
docs/implementation-coverage.md
example/ios/Podfile.lock
example/ios/QuickCryptoExample.xcodeproj/project.pbxproj
example/package.json
example/src/fixtures/aes_cbc.ts
example/src/fixtures/aes_ctr.ts
example/src/fixtures/aes_gcm.ts
example/src/fixtures/keys/ec_p256_private.ts
example/src/fixtures/keys/ec_p256_public.ts
example/src/fixtures/rsa.ts
example/src/hooks/useTestsList.ts
example/src/tests/subtle/deriveBits.ts
example/src/tests/subtle/digest.ts
example/src/tests/subtle/encrypt_decrypt.ts
example/src/tests/subtle/generateKey.ts
example/src/tests/subtle/import_export.ts
example/src/tests/subtle/sign_verify.ts
example/src/tests/util.ts
packages/react-native-quick-crypto/cpp/keys/HybridKeyObjectHandle.cpp
packages/react-native-quick-crypto/src/hash.ts
packages/react-native-quick-crypto/src/index.ts
packages/react-native-quick-crypto/src/keys/classes.ts
packages/react-native-quick-crypto/src/keys/index.ts
packages/react-native-quick-crypto/src/keys/utils.ts
packages/react-native-quick-crypto/src/subtle.ts
packages/react-native-quick-crypto/src/utils/index.ts
packages/react-native-quick-crypto/src/utils/types.ts
packages/react-native-quick-crypto/src/utils/validation.ts

- copy `0.x` code for `crypto.subtle` API to `main`
- adapt to new types/classes structure
- copy `0.x` tests for `crypto.subtle` API
- adapt tests to new structure
✅ `deriveBits`
✅ `digest`
❌ `encrypt/decrypt`
❌ `generateKey`
❌ `import/export`
❌ `sign/verify`
Subsequent PRs will implement native functionality until we have parity with `0.x` and tests pass.  Until then, `main` is kinda broken.

feat: add `subtle` code and tests from 0.x
